name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:
  build:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v3

    - name: cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{env.INSTALL_LOCATION}}
        key: ${{runner.os}}-dependencies

    - name: install GoogleTest
      if: ${{steps.cache.output.cache-hit != 'true'}}
      run: |
        cd ..
        git clone https://github.com/google/googletest.git --branch v1.13.x
        cd googletest
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX="$HOME/$env:INSTALL_LOCATION" -Dgtest_force_shared_crt=1
        cmake --build build --config Release
        cd ../${{ github.event.repository.name }}

    - name: configure
      run: cmake -B build -DCMAKE_INSTALL_PREFIX="$HOME/$env:INSTALL_LOCATION"
      
    - name: build
      run: cmake --build build --config "$env:BUILD_TYPE" -j4

    - name: run tests
      run: |
        cd build
        ctest -C "$env:BUILD_TYPE" -VV

